spring.data.mongodb.uri=mongodb+srv://kutwalsaurabh19:test1903@cluster0.aagfgos.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.port=27017
#spring.data.mongodb.host=mongodb+srv://<credentials>@cluster0.aagfgos.mongodb.net
spring.data.mongodb.database=JournalDB
#spring.data.mongodb.username=kutwalsaurabh19
#spring.data.mongodb.password=ACE19@mongodb